name: Obsidian-Armor
author: JordanG8
description: A Slimefun addon that adds obsidian armor
main: me.jordang8.obsidianarmor.Main
website: https://github.com/JordanG8/Obsidian-Armor
depend: [Slimefun]
version: 1.0.0
api-version: 1.14
